import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const font = Geist();

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function ({ children }: LayoutProps<"/">) {
  return (
    <html className="antialiased" lang="en" suppressHydrationWarning>
      <body className={font.className}>{children}</body>
    </html>
  );
}
