import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const font = Geist();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="antialiased"
    >
      <body className={font.className}>{children}</body>
    </html>
  );
}
